name: support issue 275

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Linux]
    # container: ubuntu:20.04
    # services:
    #   postgres:
      

    steps:

   
      - name: cache clear
        run: |
         mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
         mkdir -p "${{ runner.tool_cache }}"
      - uses: actions/checkout@v4

      

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          

      - name: Python install
        
        run: |
          # pip install
          python --version
          python -m pip install -U pip "setuptools<72.1.0" wheel pytest pytest-cov  --ignore-installed
          python -m pip install -r requirements.txt --ignore-installed         
      - name: Install poetry
        run: |
          python -m pip install poetry==1.8.3
      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true
      - name: Upgrade pip
        run: |
          python -m poetry run pip install --upgrade pip
      - name: Cache the virtualenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv1-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          python -m poetry install
